### ISSUE TITLE
Change name to gennodejs

### ISSUE THREAD

**Issue by IanTheEngineer** [RethinkRobotics-opensource/genjs#5]
After a discussion on [ROS REP 142](https://github.com/ros-infrastructure/rep/pull/113), it seems the consensus-building move is to change the name of this repository and package to `gennodejs`. To do this:
- [x] Change the name of this repository and update all git remotes
- [x] Update `message_generation` to depend on `gennodejs` rather than `genjs`
- [x] Update the `ros-core` REP 142 with `gennodejs` rather than `genjs`
- [x] Update any `genjs` names in this repo to `gennodejs`
- [x] Rename the release repo as `gennodejs-release`
- [x] Bloom this package up to `rosdistro` as `gennodejs`
- [x] Submit a custom pull request to `rosdistro` to remove `genjs` and add `gennodejs`
- [x] Kindly ask Tully to remove the old docs and debs for `genjs`

**Comment by IanTheEngineer** [comment]
Resolved by submitting to `rosdistro`: https://github.com/ros/rosdistro/pull/11319

**Comment by IanTheEngineer** [comment]
Reopened pending https://github.com/ros/message_generation/pull/4 merge

**Comment by dirk-thomas** [comment]
ros/message_generation#4 has been merged and released (ros/rosdistro#11334). Can you please also add a note to the Kinetic migration page (http://wiki.ros.org/kinetic/Migration) mentioning that gennodejs has been added as a default generator and maybe linking its wiki page or any further documentation how to use it with node js.

**Comment by IanTheEngineer** [comment]
Thanks Dirk! I have added `gennodejs` to the Kinetic Migration guide with a basic explanation. We intend to fill this out more along with `gennodejs` and `rosnodejs` wiki pages in the coming days / weeks.
